In [39]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd
import numpy as np

In [61]:
df = pd.DataFrame({'a':['a1, a2, c2','a2, b2','c1, c2']})
df

a
0  a1, a2, c2
1      a2, b2
2      c1, c2

In [73]:
df = pd.DataFrame({'a':['a','b','a']})

In [ ]:
#freq feature
asidc=train['ad_slot_id'].value_counts()
fs=asidc[asidc>1]
fs=pd.cut(fs, bins=10,labels=False)
fs

In [7]:
vectorizer = CountVectorizer()
X=vectorizer.fit_transform(df['a'])
X.toarray()

array([[1, 1, 0, 0, 1],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1]], dtype=int64)

In [40]:
tfidfvect = TfidfVectorizer()
tfidf=tfidfvect.fit_transform(df['a'])
tfidf.toarray()

array([[ 0.68091856,  0.51785612,  0.        ,  0.        ,  0.51785612],
       [ 0.        ,  0.60534851,  0.79596054,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.79596054,  0.60534851]])

In [9]:
df2 = pd.DataFrame({'a':['win_chrome','win_explorer','linux_opera','linux_chrome','win_chrome']})
df2

a
0    win_chrome
1  win_explorer
2   linux_opera
3  linux_chrome
4    win_chrome

In [11]:
X2 = vectorizer.fit_transform(df2['a'])
X2.toarray()

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0]], dtype=int64)

In [60]:
df2['a2']=df2['a'].map(lambda x: x.split("_"))
df2['a3']=df2['a2'].map(lambda x: x[0])
df2['a4']=df2['a2'].map(lambda x: x[1])
df2
# X3=vectorizer.fit_transform(df2['a3'])
# dfx3=pd.DataFrame(X3.toarray(),columns=vectorizer.vocabulary_.keys())
# X4=vectorizer.fit_transform(df2['a4'])
# dfx4=pd.DataFrame(X4.toarray(),columns=vectorizer.vocabulary_.keys())
# rtn=pd.concat([dfx3,dfx4],axis=1)
# rtn

a               a2     a3        a4
0    win_chrome    [win, chrome]    win    chrome
1  win_explorer  [win, explorer]    win  explorer
2   linux_opera   [linux, opera]  linux     opera
3  linux_chrome  [linux, chrome]  linux    chrome
4    win_chrome    [win, chrome]    win    chrome

In [33]:
df4=pd.DataFrame({'h':[1,2,3,4,5,6],'w':[4,5,2,1,6,7]})
df4['a']=df4['h']*df4['w']
df4

h  w   a
0  1  4   4
1  2  5  10
2  3  2   6
3  4  1   4
4  5  6  30
5  6  7  42

In [48]:
dfa = pd.DataFrame({'t':[20130606000104308,20130606000104308,20130606054424308,20130606000104233]})
dfa['ty']=dfa['t'].map(lambda x: str(x)[0:4])
dfa['tm']=dfa['t'].map(lambda x: str(x)[4:6])
dfa['td']=dfa['t'].map(lambda x: str(x)[6:8])
dfa

t    ty  tm  td
0  20130606000104308  2013  06  06
1  20130606000104308  2013  06  06
2  20130606054424308  2013  06  06
3  20130606000104233  2013  06  06

In [57]:
dfb = pd.DataFrame({'h':np.random.randint(0,24,size=100)})
dfb['qh']=pd.cut(dfb['h'], bins=6,labels=False)
dfb.head()

h  qh
0   2   0
1   7   1
2   0   0
3   6   1
4  10   2